### ISSUE TITLE
Error - uninitialized constant TiendasController::Provincias

### ISSUE THREAD

**Issue by sergibyte** [javiertoledo/provincias#1]
Hola,
he seguido las instrucciones para instalar la gema añadiéndola al Gemfile, pero tras ejecutar bundle e intentar acceder a una provincia en mi controlador, recibo el error uninitialized constant TiendasController::Provincias.

Uso Rails 4.2.3.

Hay algo que esté pasando por alto?

Gracias.

**Comment by sergibyte** [comment]
Reiniciar el servidor! Eso es lo que pasaba por alto.

Disculpa las molestias y muchas gracias por esta gema, es genial!

**Comment by javiertoledo** [comment]
Eso nos ha pasado a todos, gracias a tí! :-D
